### DISCUSSION TITLE
Sensors don't persist between Home Assistant restarts

### DISCUSSION THREAD

**Discussion by Icexist** [AntoineGS/teams-status-rs#14] [Q&A] [answered]
Great tool, super fast updating and easy to configure.

One quirk I noticed, however, was that the sensors created by the tool don't persist between Home Assistant restarts and don't re-appear until a new Teams meeting is joined. Is there a config choice somewhere either in HA or this tool that can keep the sensors? Should I create sensors with the same name in HA?

**Comment by AntoineGS** [comment]
Thanks!
Yeah I find this annoying too, I meant to document this after my current feature (parsing the teams logs to get additional data).
You can get it to persist using the MQTT integration or by creating them in HA manually like you mentioned.
In my previous integration I had the steps to manually add them, it is the first step here: https://github.com/AntoineGS/TeamsStatusV2?tab=readme-ov-file#installation
The id and name for each sensor is in the conf.ini file that the application generates, the unique ID you can probably just use a random one for each.

**Reply by Icexist** [reply]
So I can create each sensor in HA with a unique ID and as long as they have the same name as the config file, they'll be updated correctly?

**Reply by AntoineGS** [reply]
I have not tested this with this version of the application but that is what I used to do and it worked well!

**Reply by Icexist** [reply, marked as answer]
Well, so far it seems to work with these template sensors:

```yaml
template:
  - binary_sensor:
    - name: teams_muted
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_video
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_hand_raised
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_meeting
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_recording
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_background_blurred
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_sharing
      unique_id: "unique"
      state: "{{ None }}"
    - name: teams_unread_messages
      unique_id: "unique"
      state: "{{ None }}"
```
