### ISSUE TITLE
The state change overrides any customizations in home assistant

### ISSUE THREAD

**Issue by anishsane** [AntoineGS/teams-status-rs#30]
I have added a customization for the teams binary_sensor entities as

```
customize_glob: !include customize.yaml
---------------------------------------
binary_sensor.teams_*:
  templates:
    icon_color: "if (state === 'on') return 'rgb(255, 0, 0)';"
```

I have a dummy teams unmuted sensor created to invert the teams muted sensor.

The customization works ok for the unmuted sensor.
However, the customization of the other sensors gets reset when their state changes.
I also tried to manually set the customization via developer tools -> states. It also got reset when there was a data push by this application.

Can we fetch the existing state and then update only the on/off part and post it back? Thereby any other state fields will be preserved.

At present, I have worked around this issue by creating a dummy sensor for each of the existing sensors in this implementation. But it will be easier if it is handled within this project itself.

**Comment by AntoineGS** [comment]
I'll see what I can do, though the HA API resets all configurations not sent through when using the API.
It might work differently with the MQTT integration though, that one might work as-is.

**Comment by anishsane** [comment]
I tried creating mqtt binary_sensors. But they don't seem to support customization like template sensors do.

(I don't wish to create an automation for this "when an mqtt-message is received" as trigger.)

Here is the snippet of my `configuration.yaml`:

```
mqtt:
  binary_sensor:
    - name: "Teams Video"
      icon: "mdi:webcam-off"
      value_template: "{{ value_json.video_on }}"
      state_topic: "teams-status"
      payload_on: "on"
      payload_off: "off"
    - name: "Teams Unmuted"
      unique_id: "teams_unmuted_123"
      value_template: "{{ value_json.muted if (value_json.in_meeting == 'on') else 'on' }}"
      state_topic: "teams-status"
      payload_on: "off"
      payload_off: "on"
      icon: 'mdi:microphone-off'
        #if (state == 'on') return 'mdi:microphone'; # Does not work. It is treated literally.
        #return 'mdi:microphone-off';

homeassistant:
  customize_glob:
    binary_sensor.teams_unmuted:
      templates:
        icon: "return 'mdi:connection-off';"
```

I also tried the known variations of the `icon:` tag under customization. But none of them worked.

**Comment by AntoineGS** [comment]
With the HA API, is the only thing missing the template?

**Comment by anishsane** [comment]
My original configuration.yaml looks like this:

```
homeassistant:
  customize_glob: !include customize.yaml


template:
  binary_sensor:
     ############## Originals from github.com/AntoineGS/teams-status-rs
      - name: "Teams Muted"
        unique_id: "ts_a7703e21-2ae1-4af5-ba77-108f2462004a"
        icon: "mdi:microphone-off"
        state: "{{ None }}"
      - name: "Teams Video"
        unique_id: "ts_38dc82bf-bc6d-491f-84c1-9fbee02641a9"
        icon: "mdi:webcam-off"
        state: "{{ None }}"
      - name: "Teams Hand Raised"
        unique_id: "ts_9e7c62d5-5640-4cfb-8ff7-4eac9922030e"
        icon: "mdi:hand-back-left-off"
        state: "{{ None }}"
      - name: "Teams Meeting"
        unique_id: "ts_74837ead-9946-49c9-8aec-f25c0c031ec5"
        icon: "mdi:phone-off"
        state: "{{ None }}"
      - name: "Teams Recording"
        unique_id: "ts_493dcc2e-7cf6-456a-95b2-8cd029b2300c"
        icon: "mdi:power-off"
        state: "{{ None }}"
      - name: "Teams Background Blurred"
        unique_id: "ts_ae97f0dd-7dc3-4f9b-bfb4-ecbc30b8957b"
        icon: "mdi:blur-off"
        state: "{{ None }}"
      - name: "Teams Sharing"
        unique_id: "ts_402f1b21-5ad5-49d2-b451-2cf1e95cab65"
        icon: "mdi:projector-screen-off"
        state: "{{ None }}"
      - name: "Teams Unread Messages"
        unique_id: "ts_61500ecd-5f28-4be4-912d-a64f306fa0cc"
        icon: "mdi:message-off"
        state: "{{ None }}"

      ####################### Extras/Duplicates for customization.  See customize.yaml.
      - name: "Teams Unmuted" ############## Invert state
        unique_id: "ts_a7703e21-2ae1-4af5-ba77-108f2462004b"
        state: '{{ is_state("binary_sensor.teams_muted","off") and is_state("binary_sensor.teams_meeting", "on")}}'
        icon: >
          {% if (is_state("binary_sensor.teams_unmuted","on")) %}
          mdi:microphone
          {% else %}
          mdi:microphone-off
          {% endif %}
      - name: "Teams Video On" ############### For customization purpose.
        unique_id: "ts_38dc82bf-bc6d-491f-84c1-9fbee02641aa"
        state: '{{ is_state("binary_sensor.teams_video","on")}}'
        icon: >
          {% if (is_state("binary_sensor.teams_video","on")) %}
          mdi:webcam
          {% else %}
          mdi:webcam-off
          {% endif %}
```


And customize.yaml looks like this:

```
red_highlight_common: &red_highlight_common
  templates:
    icon_color: "if (state === 'on') return 'rgb(255, 0, 0)';"

binary_sensor.teams_*: *red_highlight_common
```

The customization works for the extra sensors mentioned above. But not for the originals.
If I reload the template entities from developer tools, I do see this in the developer-tools/state:


|![image](https://github.com/user-attachments/assets/e07a0a0e-527a-4319-87f3-d1fb0686ed94)|
|-|


However, when there is a push from the windows app, the `templates` section from the attribute disappears.
